### ISSUE TITLE
Ignore parent groups in URL to only ignore parent groups.

### ISSUE THREAD

**Issue by kasperlegarth** [dynamicweb/DynamicWeb#164]
**Is your feature request related to a problem? Please describe.**
On products group, when checking the field "Ignore parent groups in URL" The product group gets placed in the root of the website. It also ignores the content part of the URL.

So if i have website -> shop (content page) -> group1 -> group2. I check the box on group2 i would expect to get website.com/shop/group2 instead i get website.com/group2

**Describe the solution you'd like**
I would like it to exactly what the labels say. Ignore "parent groups" in the URL. Not everything that comes before.

**Comment by nicped** [comment]
It is actually the label that is wrong. The underlying property is called UrlIgnoreParent which place the group in the root of the navigation tree. Changing the bahavior of the checkbox would not be a good idea since that would break a lot of websites current URL structure and that would not be fun...

So I guess the request is to being able to flatten the group structure regardless of the page.
The way it works for pages, is that on the parent you can leave the parent out on sub URLs using the "Do not include URL in subpage URLs" on a page.

If we moved that feature to groups, pages and groups would have the same options. It would work like this:

- Bikes ("Do not include URL in subgroup URLs")
  - Mountain Bike
  - Road bike

Setting the "Do not include URL in subgroup URLs" on the Bike parent group, would result in these 3 urls:
- /bikes
- /mountain-bikes
- /road-bikes

And if not setting that new checkbox would result in
- /bikes
- /bikes/mountain-bikes
- /bikes/road-bikes

This approach makes it easier to setup and new sub groups would automatically also be placed a level down the structure.
The downside is that you can not mix for each sub group to create a URL structure like this:
- /bikes
- /mountain-bikes
- /bikes/road-bikes

But I guess that is not a problem....?

Let me know what you think about this.

**Comment by kasperlegarth** [comment]
Hi Nicolai.
I see. I falsely assumed that it was the incorrect function. because in DW9 i worked as i thought i should.

For your solution proposal. That would be ideal for my use case. It is in fact two top-level groups i would like to leave out of the URL. So for me, it would change from about 20 checkboxes to only two.

I do agree that this would be the better solution because it would be easier to maintain. And i think it will add more flexibility to build content around the ecom.

**Comment by nicped** [comment]
Thanks for clarifying.

I think looking at a new option that behaves like in content is the way to go.

**To clarify the differences between 9 and 10**
In DW9 it works the same - but in DW9 there are 2 URL systems - the 'old' one and the 'new' one. Only the new one exists on DW10 and here it behaves the same as on DW9. The old URL system of DW9 is 2 URL structures - one for ecommerce and one for content, so setting that checkbox in the old system would put the URL to the root of groups. If you had groups on level 2, 3, 4 etc. all of them would be placed in the URL root.

**Comment by kasperlegarth** [comment]
I agree that it would be the way to go.
Like everyone else would say, of course, my problem is the most important in the world 😅😉

Jokes aside, to be curious, what is the process from here? And is there an acceptance debate, some planning, etc.?

**Comment by nicped** [comment]
I have moved this to 21526 in our devops - I think this task is relatively small and it will be handled on the next PM meeting.

Do not expect it before earliest 10.10 around december.

**Comment by kasperlegarth** [comment]
Hi Nicolai.

Is this still on track for 10.10? 
We have a customer who is asking specifically for this feature.
Can i promise them, that it is coming in release 10.10?

**Comment by nicped** [comment]
Even better. I think it made it to 10.9

![image](https://github.com/user-attachments/assets/5d60e471-3055-406a-bcb0-5dab9c406ce3)

**Comment by kasperlegarth** [comment]
@nicped Do you happen to be on an future release?
I just updated to 10.9.1. The feature is not there?

**Comment by nicped** [comment]
Yes - I have main branch which is the next 10.10. I can see the merge to main was made before the release of 10.9, but 10.9 was branched out before - so it will be in 10.10 as originally promised. That will release on November 26th.

**Comment by kasperlegarth** [comment]
Hi @nicped 
Sounds great. Is there any way to accelerate it down the release rings? We plan on going on release ring 3, to be sure we have a stable solution. The project is set to launch in December.

**Comment by nicped** [comment]
We are strictly following the policy described here: [https://doc.dynamicweb.dev/documentation/fundamentals/dw10release/releasepolicy.html](https://doc.dynamicweb.dev/documentation/fundamentals/dw10release/releasepolicy.html)

Everyone wants their things on their version which would ultimately lead to everyone having all features and bugfixes on all versions... And that would being the same as running on R1...

New features are only added to new versions - bugfixes trickles down according to the bug fixing policy. This is to ensure that existing minor versions have as little change as possible to avoid unwanted side effects.

**Comment by kasperlegarth** [comment]
Fair enough.
So we expect it to be part of R3 on the last Tuesday of January?

**Comment by nicped** [comment]
Yes!
