### ISSUE TITLE
Edit option for link editor

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#207]
The change to link editor that removed the option to edit the value has been met with critisism from one of our customers
![image](https://github.com/user-attachments/assets/d8437189-80fd-4c19-a055-e8f9995c5ffe)
They request an option to change the currently selected link instead of being forced to replace

**Comment by nicped** [comment]
Can you elaborate? If you choose external link, you can write whatever you want. If you link to a page, we want you to select a page so we ensure that you choose and ID that is correct. Is what they are looking for being able to change the "Default.aspx?ID=123" to "Default.aspx?ID=321" in the edit mode?

**Comment by ivaigor96** [comment]
What they are talking about is "better user experience". No matter what is selected already, they think good UX is that you can edit the current selected thing e.g. chose another page or change the external link. They like the way the editors are themselves, but they are saying for example if the external link is set - google.com, they want to click edit and then have the google.com there in the input field, not that they have to select external link, it will be blank and then type again. They expect to be able to change the thing that is already there or remove it. Only after removing it they expect adding a different type of link e.g. instead of page they want to type external link. So it's just a different expectations from the UI, both are valid how we have now and how they want

**Comment by ivaigor96** [comment]
I think the main problem is these automatic updates, they keep getting used to something and then getting upset that it is changed, for example like that table editor we lost. It should be a consideration when changing the UI that it is not for new projects only, it is for existing customers doing a lot of changes and being very conservative and picky, even if it's an improvement they might not like it because it removes something old that was possible

**Comment by nicped** [comment]
That would basically mean that we can never change anything, We could stop development :-).
It is the same in most software - you get changes. We have introduced feature flags that we use for major changes so you have to opt-in, but for smaller things like this, it will be released.

The particular change of the link editor has been given a lot of thought and effort. It is inspired by how the most popular systems out there handles links these days and is based on the overall input we have received from users.

The missing table on RTE - yes, that is an issue. We had to change the editor because of license change from the supplier of the old one and did not catch the table feature as we do not use it by default because tables is rarely used on modern websites because of its lacking ability to function properly on mobile viewports which is give or take 50% of all website visitors.

**Comment by ivaigor96** [comment]
I will forward the response that the decision for this editor is based on data and that changes are expected in the future updates. I also agree that it is not a big deal, it is just a different way of thinking

**Comment by nicped** [comment]
Cool - and we will have a look at improving the editing external links in the link editor

**Comment by nicped** [comment]
Edit of external link implemented in devops#22435
